# -*- coding: utf-8 -*-
"""3A-ORELLANO-EXER1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fQOvDdlHfBwe9TAishtYCY0ljNuEL0PK

# **Exercise 1: Propositional Logic in Python**
"""

rains = True
wet = rains
lights = not wet

if lights:
    print("The match will light.")
else:
    print("The match will not light.")

"""# **Exercise 2: Predicate Logic Representation**"""

def isHuman(name):
    return name == "Socrates"

def isMortal(name):
    return isHuman(name)

if isMortal("Socrates"):
    print("Socrates is mortal.")

"""# **Exercise 3: Inference Techniques in Logic-Based Systems**

"""

def modus_ponens(rule, fact):
    if rule[0] == fact:
        return rule[1]
    return None

rule = ("X", "Y")
fact = "X"
conclusion = modus_ponens(rule, fact)

if conclusion:
    print(f"The conclusion is: {conclusion}")

"""# **Exercise 4: Hands-on Lab - Implementing a Logic-Based Model in Python**"""

hungry = True

if hungry:
    print("John will eat.")
    hungry = False

if not hungry:
    print("John is no longer hungry.")

"""# **Assignment: Implement a Logic-Based Model in Python**"""

class Voter:
    def __init__(self, registered, age, citizen, voted_last_election):
        self.registered = registered
        self.age = age
        self.citizen = citizen
        self.voted_last_election = voted_last_election

    def can_vote(self):
        return (self.registered and
                self.age >= 18 and
                self.citizen and
                not self.voted_last_election)

    def eligibility_status(self):
        if not self.registered:
            return "Not registered to vote."
        elif self.age < 18:
            return "Not old enough to vote."
        elif not self.citizen:
            return "Not a citizen."
        elif self.voted_last_election:
            return "Already voted in the last election."
        else:
            return "Eligible to vote."

def main():
    registered = input("Is the voter registered? (yes/no): ").strip().lower() == 'yes'
    age = int(input("Enter the voter's age: "))
    citizen = input("Is the voter a citizen? (yes/no): ").strip().lower() == 'yes'
    voted_last_election = input("Did the voter vote in the last election? (yes/no): ").strip().lower() == 'yes'

    voter = Voter(registered, age, citizen, voted_last_election)

    print("Can the voter vote?", voter.can_vote())
    print("Eligibility Status:", voter.eligibility_status())

if __name__ == "__main__":
    main()